describe('CSS Locator',()=>{
    it('CSS Locators', ()=>{
        cy.visit("https://www.saucedemo.com/")
        cy.get('input[type="text"]').type('standard_user')
        cy.get('input[id="password"]').type('secret_sauce')
        cy.get('input[id="login-button"]').click()
        cy.get('[class="product_sort_container"]').select('lohi')
        cy.get('[id="add-to-cart-sauce-labs-onesie"]').click()
        cy.get('[class="shopping_cart_link"]').click()
        cy.get('[id="checkout"]').click()
        cy.get('[id="first-name"]').type('Deena Hari')
        cy.get('[id="last-name"]').type('H')
        cy.get('[id="postal-code"]').type('632602')
        cy.get('[id="continue"]').click()
        cy.get('[class="summary_subtotal_label"]').should('contain','Item total: $7.99')
        cy.get('[id="finish"]').click()
        cy.get('[class="complete-header"]').should('contain'),('Thank you for your order!')
    })
})